#!/usr/bin/env python3
"""
Pipeline Architecture Pattern Parsing Script
--------------------------------------------

Purpose
-------
Parses previously audited OpenAlex paper corpora in order to identify
high-level machine learning pipeline and architectural design patterns
across the four prediction regimes:

    S = structured multiscale prediction
    H = high-dimensional biomedical signals
    M = multimodal learning
    T = temporal and longitudinal modeling

Unlike the original OpenAlex retrieval pipeline, this script DOES NOT
query OpenAlex again. Instead, it operates on already curated and
audited paper collections generated by the earlier parsing stages.

The script:
1) loads regime-specific paper audit logs
2) identifies accessible/analyzable papers using audit inclusion flags
3) recovers metadata and abstracts from the original OpenAlex CSV exports
4) optionally retrieves DOI landing pages and PDF full text
5) extracts large-scale architectural and pipeline-design patterns
6) builds prevalence statistics using accessible papers as denominators
7) exports:
      - prevalence tables
      - raw count tables
      - audit logs with evidence snippets
      - dataset-level coverage summaries
      - LaTeX tables
      - JSON parsing reports

Pipeline architecture categories detected
-----------------------------------------
The script detects five major architectural/pipeline pattern classes:

1. Handcrafted feature pipelines
2. Learned representation pipelines
3. Fusion-centric architectures
4. Sequential predictive pipelines
5. Robust / transfer-aware pipelines

Default data flow
-----------------
Audit log input:
    regime_parse_outputs/<REGIME>/<REGIME>_paper_audit_log.csv

Optional metadata recovery:
    query_outputs/<REGIME>/openalex_*_<REGIME>_ml_top350.csv

"""

from __future__ import annotations

import argparse
import concurrent.futures as cf
import io
import json
import os
import re
import sys
import time
import warnings
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple
from urllib.parse import urljoin

import pandas as pd

import logging
logging.getLogger("PyPDF2").setLevel(logging.ERROR)

try:
    import requests
except Exception:  # pragma: no cover
    requests = None

try:
    from bs4 import BeautifulSoup
except Exception:  # pragma: no cover
    BeautifulSoup = None

try:
    from PyPDF2 import PdfReader
except Exception:  # pragma: no cover
    PdfReader = None

try:
    from tqdm.auto import tqdm
    tqdm.monitor_interval = 0
except Exception:  # pragma: no cover
    tqdm = None

warnings.filterwarnings("ignore")

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0 Safari/537.36"
)

# -----------------------------------------------------------------------------
# Pattern taxonomy
# -----------------------------------------------------------------------------
# Pattern names are intentionally concise because they become table rows.
PIPELINE_PATTERNS_RAW = [

# =========================================================
# 1. HANDCRAFTED FEATURE PIPELINES
# =========================================================
("Handcrafted feature pipelines",[

r"\bfeature engineering\b",
r"\bhandcrafted features?\b",
r"\bhand[- ]crafted features?\b",
r"\bengineered features?\b",
r"\bmanual feature extraction\b",

r"\bfeature selection\b",
r"\bfeature screening\b",
r"\bfeature ranking\b",
r"\bfeature construction\b",
r"\bfeature design\b",

r"\bradiomic features?\b",
r"\bradiomics\b",
r"\btexture features?\b",
r"\bmorphological features?\b",
r"\bshape descriptors?\b",

r"\bwavelet features?\b",
r"\bspectral features?\b",
r"\bfrequency-domain features?\b",
r"\btime-domain features?\b",

r"\bbiomarker panel\b",
r"\bengineered predictors?\b"

]),


# =========================================================
# 2. LEARNED REPRESENTATION PIPELINES
# =========================================================
("Learned representation pipelines",[

r"\brepresentation learning\b",
r"\blearned representation(s)?\b",
r"\blearned feature representation(s)?\b",
r"\blearned latent representation(s)?\b",
r"\blatent representation(s)?\b",
r"\blatent space\b",
r"\blatent embedding(s)?\b",
r"\blatent feature(s)?\b",

r"\bembedding learning\b",
r"\blearned embedding(s)?\b",
r"\bfeature embedding(s)?\b",
r"\bpatient embedding(s)?\b",
r"\bjoint embedding(s)?\b",
r"\bshared embedding(s)?\b",

r"\bautoencoder(s)?\b",
r"\bauto-encoder(s)?\b",
r"\bvariational autoencoder(s)?\b",
r"\bvariational auto-encoder(s)?\b",
r"\bVAE\b",
r"\bdenoising autoencoder(s)?\b",
r"\bsparse autoencoder(s)?\b",

r"\bself-supervised learning\b",
r"\bcontrastive learning\b",
r"\bcontrastive embedding(s)?\b",

r"\bdeep feature learning\b",
r"\bdeep feature extraction\b",
r"\bdeep feature(s)?\b",
r"\bfeature learning\b",

r"\bpretrained representation\b",
r"\bpre-trained representation\b",
r"\bpretrained encoder\b",
r"\bpre-trained encoder\b",

r"\bfoundation model\b",
r"\bencoder-decoder\b",
r"\bencoder decoder\b",

r"\btransformer encoder\b",
r"\bgraph embedding(s)?\b",
r"\bnode embedding(s)?\b",
r"\bsequence embedding(s)?\b",
r"\bimage embedding(s)?\b",
r"\btext embedding(s)?\b",

r"\bdimensionality reduction\b",
r"\bmanifold learning\b"

]),

# =========================================================
# 3. FUSION-CENTRIC ARCHITECTURES
# =========================================================
("Fusion-centric architectures",[

r"\bmultimodal fusion\b",
r"\bmulti[- ]modal fusion\b",
r"\bfusion model\b",
r"\bfusion architecture\b",
r"\bfusion framework\b",
r"\bfusion network\b",

r"\bearly fusion\b",
r"\blate fusion\b",
r"\bintermediate fusion\b",
r"\bhybrid fusion\b",
r"\bfeature fusion\b",
r"\bdecision fusion\b",
r"\bscore fusion\b",

r"\btensor fusion\b",
r"\bmultimodal transformer\b",

r"\bcross[- ]modal attention\b",
r"\bcross modality attention\b",
r"\bcross[- ]modal\b",
r"\bco[- ]attention\b",
r"\battention fusion\b",

r"\bjoint representation learning\b",
r"\bmultimodal integration\b",
r"\bmulti[- ]modal integration\b",

r"\bmultiview learning\b",
r"\bmulti[- ]view learning\b",
r"\bmulti[- ]view fusion\b"

]),


# =========================================================
# 4. SEQUENTIAL PREDICTIVE PIPELINES
# =========================================================
("Sequential predictive pipelines",[

r"\btwo-stage model\b",
r"\btwo stage model\b",
r"\btwo-stage prediction\b",
r"\btwo step model\b",

r"\bmulti-stage model\b",
r"\bmultistage model\b",
r"\bmulti-stage prediction\b",
r"\bmulti-step prediction\b",

r"\bstacked model\b",
r"\bstacked classifier\b",
r"\bstacked generalization\b",
r"\bstacked ensemble\b",
r"\bstacking ensemble\b",

r"\bcascade(d)? model\b",
r"\bcascade(d)? prediction\b",
r"\bcascaded pipeline\b",

r"\bhierarchical model\b",
r"\bhierarchical prediction\b",
r"\bhierarchical pipeline\b",

r"\bcoarse-to-fine\b",
r"\bcoarse to fine\b",

r"\bsequential prediction\b",
r"\bprogressive prediction\b",
r"\bprogressive learning\b",

r"\bstage[- ]1\b.*\bstage[- ]2\b",
r"\bfirst[- ]stage model\b",
r"\bsecond[- ]stage model\b",

r"\bprediction.*fed into\b",
r"\bpredicted .* used as (?:an )?input\b",
r"\boutput of .* used as (?:an )?input\b",
r"\brisk score.*used as (?:an )?input\b",

r"\bmeta-classifier\b",
r"\bmeta classifier\b",
r"\bmeta-learner\b"

]),

# =========================================================
# 5. ROBUST / TRANSFER-AWARE PIPELINES
# =========================================================
("Robust / transfer-aware pipelines",[

r"\bknowledge distillation\b",
r"\bdistillation\b",
r"\bteacher-student\b",
r"\bteacher student\b",
r"\bteacher model\b.*\bstudent model\b",
r"\bstudent network\b",
r"\bdistilled model\b",

r"\bmodel compression\b",
r"\bmodel pruning\b",
r"\bquantization aware\b",

r"\bmissing modality\b",
r"\bmissing modalities\b",
r"\bmissing-modality\b",
r"\bpartial modality\b",
r"\bincomplete modality\b",

r"\bmodality dropout\b",
r"\bmodality imputation\b",
r"\bmodality invariant\b",
r"\bmodality-invariant\b",

r"\brobust multimodal\b",
r"\brobust fusion\b",
r"\bgraceful degradation\b"

])

]

PATTERN_ORDER = [name for name, _ in PIPELINE_PATTERNS_RAW]
PIPELINE_PATTERNS=[
 (n,[re.compile(p,re.I) for p in pats])
 for n,pats in PIPELINE_PATTERNS_RAW
]

HTML_TEXT_LIMIT = 200_000
PDF_PAGE_LIMIT = 25


def norm_bool_series(s: pd.Series) -> pd.Series:
    if s.dtype == bool:
        return s.fillna(False)
    return s.astype(str).str.strip().str.lower().isin(["true", "1", "yes", "y", "t"])


def detect_accessible_flag(df: pd.DataFrame, requested: str = "") -> str:
    if requested:
        if requested not in df.columns:
            raise ValueError(f"Requested --accessible-flag '{requested}' not found in audit log columns.")
        return requested
    for c in ["include_any_use", "used_any", "include_primary_only", "used_primary"]:
        if c in df.columns:
            return c
    raise ValueError(
        "Could not detect accessible-paper flag. Expected one of: "
        "include_any_use, used_any, include_primary_only, used_primary. "
        "Pass --accessible-flag explicitly if your audit log uses another column."
    )


def slug_dataset_from_filename(path: Path, regime: str) -> str:
    name = path.stem.lower()
    name = re.sub(r"^openalex_", "", name)
    name = re.sub(rf"_{regime.lower()}_ml_top\d+$", "", name)
    return name


def choose_column(df: pd.DataFrame, candidates: Sequence[str]) -> Optional[str]:
    lower = {str(c).lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower:
            return lower[cand.lower()]
    return None


def normalize_doi_url(value: str) -> str:
    value = str(value or "").strip()
    if not value or value.lower() in {"nan", "none", "na"}:
        return ""
    # Keep first DOI/URL if multiple values were serialized.
    parts = [p.strip() for p in re.split(r"[;\n\t]+", value) if p.strip()]
    value = parts[0] if parts else value
    if value.startswith("10."):
        return "https://doi.org/" + value
    return value


def normalize_title_key(title: str) -> str:
    title = str(title or "").lower()
    title = re.sub(r"[^a-z0-9]+", " ", title)
    return re.sub(r"\s+", " ", title).strip()


def clean_text(text: str) -> str:
    text = str(text or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = text.replace("&amp;", "&")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def load_openalex_metadata(openalex_dir: Path, regime: str) -> Dict[Tuple[str, str], Dict[str, str]]:
    """Return mapping (dataset, normalized_title) -> metadata dict."""
    mapping: Dict[Tuple[str, str], Dict[str, str]] = {}
    for path in sorted(openalex_dir.glob(f"openalex_*_{regime}_ml_top*.csv")):
        dataset = slug_dataset_from_filename(path, regime)
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        title_col = choose_column(df, ["title", "display_name"])
        abstract_col = choose_column(df, ["abstract"])
        doi_col = choose_column(df, ["doi", "DOI", "doi_url", "url", "link", "links"])
        openalex_col = choose_column(df, ["openalex_id", "id"])
        year_col = choose_column(df, ["year", "publication_year"])
        if title_col is None:
            continue
        for _, row in df.iterrows():
            title = clean_text(row.get(title_col, ""))
            key = (dataset, normalize_title_key(title))
            if not key[1]:
                continue
            mapping[key] = {
                "title_oa": title,
                "abstract": clean_text(row.get(abstract_col, "")) if abstract_col else "",
                "doi_or_url_oa": normalize_doi_url(row.get(doi_col, "")) if doi_col else "",
                "openalex_id": clean_text(row.get(openalex_col, "")) if openalex_col else "",
                "year_oa": clean_text(row.get(year_col, "")) if year_col else "",
                "source_csv": path.name,
            }
    return mapping


def extract_method_like_text(text: str, window: int) -> str:
    if window <= 0:
        return text
    lower = text.lower()
    headings = [
        "methods", "materials and methods", "methodology", "model", "models",
        "model architecture", "architecture", "approach", "framework", "pipeline",
        "experiments", "implementation", "statistical analysis", "machine learning",
    ]
    chunks = []
    for h in headings:
        for m in re.finditer(re.escape(h), lower):
            start = max(0, m.start() - window // 3)
            end = min(len(text), m.end() + window)
            chunks.append(text[start:end])
            if len(chunks) >= 12:
                break
        if len(chunks) >= 12:
            break
    if not chunks:
        return text
    # Include title/abstract beginning plus method-like chunks.
    return (text[:4000] + " " + " ".join(chunks))[:100_000]

def detect_pipeline_patterns(text, method_window=8000):
    target = extract_method_like_text(text, method_window)
    found = []
    evidence = {}

    for name, pats in PIPELINE_PATTERNS:

        for pat in pats:
            m = pat.search(target)
            if m:
                found.append(name)
                evidence[name] = re.sub(
                    r"\s+",
                    " ",
                    target[max(0, m.start()-120):min(len(target), m.end()+180)]
                ).strip()
                break

    return found, evidence

@dataclass
class FetchResult:
    text: str
    source: str
    url: str
    error: str = ""


class FullTextFetcher:
    def __init__(self, timeout: int, sleep_sec: float):
        self.timeout = timeout
        self.sleep_sec = sleep_sec
        self.session = None
        if requests is not None:
            self.session = requests.Session()
            self.session.headers.update({"User-Agent": USER_AGENT})

    def fetch(self, url: str) -> FetchResult:
        url = normalize_doi_url(url)
        if not url or not re.match(r"https?://", url, flags=re.I):
            return FetchResult("", "metadata_only", url, "no_url")
        if self.session is None:
            return FetchResult("", "metadata_only", url, "requests_unavailable")
        try:
            time.sleep(self.sleep_sec)
            r = self.session.get(url, timeout=self.timeout, allow_redirects=True)
            r.raise_for_status()
        except Exception as e:
            return FetchResult("", "metadata_only", url, f"request_failed:{type(e).__name__}")

        ctype = (r.headers.get("Content-Type") or "").lower()
        final_url = r.url
        if "pdf" in ctype or final_url.lower().split("?")[0].endswith(".pdf"):
            txt = extract_pdf_text(r.content)
            return FetchResult(txt, "pdf", final_url, "" if txt else "pdf_no_text")

        html = r.text or ""
        html_text = extract_html_text(html)
        pdf_url = find_pdf_url(final_url, html)
        if pdf_url:
            try:
                time.sleep(self.sleep_sec)
                pr = self.session.get(pdf_url, timeout=self.timeout, allow_redirects=True)
                if pr.ok and ("pdf" in (pr.headers.get("Content-Type") or "").lower() or pr.url.lower().split("?")[0].endswith(".pdf")):
                    pdf_text = extract_pdf_text(pr.content)
                    if pdf_text:
                        combined = clean_text(html_text + " " + pdf_text)
                        return FetchResult(combined, "html_plus_pdf", pr.url, "")
            except Exception:
                pass
        return FetchResult(html_text, "html", final_url, "" if html_text else "html_no_text")


def extract_html_text(html: str) -> str:
    if not html or BeautifulSoup is None:
        return ""
    try:
        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style", "noscript", "svg"]):
            tag.decompose()
        pieces = []
        for meta_name in ["citation_title", "description", "citation_abstract", "dc.description"]:
            tag = soup.find("meta", attrs={"name": meta_name})
            if tag and tag.get("content"):
                pieces.append(tag["content"])
        for meta_prop in ["og:title", "og:description"]:
            tag = soup.find("meta", attrs={"property": meta_prop})
            if tag and tag.get("content"):
                pieces.append(tag["content"])
        for tag in soup.find_all(["title", "h1", "h2", "h3", "p", "section", "article", "li"]):
            txt = tag.get_text(" ", strip=True)
            if txt and len(txt) > 20:
                pieces.append(txt)
        return clean_text(" ".join(pieces))[:HTML_TEXT_LIMIT]
    except Exception:
        return ""


def find_pdf_url(base_url: str, html: str) -> str:
    if not html or BeautifulSoup is None:
        return ""
    try:
        soup = BeautifulSoup(html, "html.parser")
        candidates = []
        for tag in soup.find_all("meta"):
            if tag.get("name", "").lower() in {"citation_pdf_url", "dc.identifier"} and tag.get("content"):
                val = tag.get("content")
                if ".pdf" in val.lower():
                    candidates.append(urljoin(base_url, val))
        for a in soup.find_all("a", href=True):
            href = a.get("href") or ""
            label = a.get_text(" ", strip=True).lower()
            if ".pdf" in href.lower() or "pdf" in label or "download" in label:
                candidates.append(urljoin(base_url, href))
        seen = set()
        for c in candidates:
            if c not in seen:
                seen.add(c)
                return c
    except Exception:
        return ""
    return ""


def extract_pdf_text(data: bytes) -> str:
    if not data or PdfReader is None:
        return ""
    try:
        reader = PdfReader(io.BytesIO(data), strict=False)
        pages = []
        for page in list(reader.pages)[:PDF_PAGE_LIMIT]:
            try:
                txt = page.extract_text() or ""
            except Exception:
                txt = ""
            if txt:
                pages.append(txt)
        return clean_text(" ".join(pages))[:HTML_TEXT_LIMIT]
    except Exception:
        return ""


def pretty_dataset_name(ds: str) -> str:
    mapping = {
        "adni": "ADNI", "eicu": "eICU", "elsa": "ELSA", "hrs": "HRS",
        "midus": "MIDUS", "mimic": "MIMIC", "mpower": "mPower", "nhanes": "NHANES",
        "noaa": "NOAA", "openaq": "OpenAQ", "radar_cns": "RADAR-CNS",
        "studentlife": "StudentLife", "tcga": "TCGA", "gtex": "GTEx",
        "camelyon": "CAMELYON", "ukb_imaging": "UKBio",
    }
    return mapping.get(ds, ds)


def counts_to_tables(
    pattern_counts: Dict[str, Counter],
    denominators: Dict[str, int],
    add_total: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    datasets = sorted(denominators.keys())
    counts_df = pd.DataFrame(index=PATTERN_ORDER, columns=datasets, dtype=int).fillna(0)
    prev_df = pd.DataFrame(index=PATTERN_ORDER, columns=datasets, dtype=float).fillna(0.0)
    for pattern in PATTERN_ORDER:
        for ds in datasets:
            count = int(pattern_counts.get(ds, Counter()).get(pattern, 0))
            n = int(denominators.get(ds, 0))
            counts_df.loc[pattern, ds] = count
            prev_df.loc[pattern, ds] = round(100.0 * count / n, 1) if n else 0.0
    if add_total:
        total_n = sum(denominators.values())
        counts_df["Total"] = [sum(int(pattern_counts.get(ds, Counter()).get(p, 0)) for ds in datasets) for p in PATTERN_ORDER]
        prev_df["Total"] = [round(100.0 * float(counts_df.loc[p, "Total"]) / total_n, 1) if total_n else 0.0 for p in PATTERN_ORDER]
    counts_df.loc["Papers (N)"] = [denominators.get(ds, 0) for ds in datasets] + ([sum(denominators.values())] if add_total else [])
    prev_df.loc["Papers (N)"] = [denominators.get(ds, 0) for ds in datasets] + ([sum(denominators.values())] if add_total else [])
    # Rename columns for readability in exported tables.
    counts_df = counts_df.rename(columns={ds: pretty_dataset_name(ds) for ds in datasets})
    prev_df = prev_df.rename(columns={ds: pretty_dataset_name(ds) for ds in datasets})
    return counts_df, prev_df


def df_to_latex(df: pd.DataFrame, caption: str, label: str) -> str:
    cols = list(df.columns)
    align = "l" + "r" * len(cols)
    lines = [
        r"\begin{table*}[ht]",
        r"\centering",
        rf"\caption{{{latex_escape(caption)}}}",
        rf"\label{{{latex_escape(label)}}}",
        rf"\begin{{tabular}}{{{align}}}",
        r"\toprule",
        r"\textbf{Pipeline pattern} & " + " & ".join(rf"\textbf{{{latex_escape(str(c))}}}" for c in cols) + r" \\",
        r"\midrule",
    ]
    for idx, row in df.iterrows():
        if idx == "Papers (N)":
            lines.append(r"\midrule")
        vals = []
        for c in cols:
            x = row[c]
            if idx == "Papers (N)":
                vals.append(str(int(float(x))))
            else:
                vals.append(f"{float(x):.1f}")
        lines.append(latex_escape(str(idx)) + " & " + " & ".join(vals) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}"])
    return "\n".join(lines)


def latex_escape(s: str) -> str:
    repl = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    for k, v in repl.items():
        s = s.replace(k, v)
    return s


def df_to_pretty_text(df: pd.DataFrame) -> str:
    show = df.copy().astype(object)
    for idx in show.index:
        for col in show.columns:
            val = show.loc[idx, col]
            if idx == "Papers (N)":
                show.loc[idx, col] = str(int(float(val)))
            else:
                show.loc[idx, col] = f"{float(val):.1f}"
    return show.to_string()


def main() -> int:
    args = parse_args()
    regime = args.regime.upper()
    audit_path = Path(args.audit_results_dir) / regime / f"{regime}_paper_audit_log.csv"
    openalex_dir = Path(args.openalex_base_dir) / regime
    out_dir = Path(args.output_dir) / regime
    out_dir.mkdir(parents=True, exist_ok=True)

    if not audit_path.exists():
        print(f"ERROR: audit log not found: {audit_path}", file=sys.stderr)
        return 1

    audit = pd.read_csv(audit_path)
    flag = detect_accessible_flag(audit, args.accessible_flag)
    audit["_accessible"] = norm_bool_series(audit[flag])
    accessible = audit[audit["_accessible"]].copy()

    if "dataset" not in accessible.columns:
        raise ValueError("Audit log must contain a 'dataset' column.")
    accessible["dataset"] = accessible["dataset"].astype(str).str.strip().str.lower()

    if not args.quiet:
        print(f"Regime: {regime}")
        print(f"Audit log: {audit_path}")
        print(f"Accessible flag: {flag}")
        print(f"Accessible papers: {len(accessible)} / {len(audit)}")
        print(f"OpenAlex metadata dir: {openalex_dir}")

    oa_map = load_openalex_metadata(openalex_dir, regime)
    if not args.quiet:
        print(f"Loaded OpenAlex metadata rows indexed by title: {len(oa_map)}")

    # Prepare rows and metadata text.
    rows = []
    for i, row in accessible.iterrows():
        ds = str(row.get("dataset", "")).strip().lower()
        title = clean_text(row.get("title", ""))
        key = (ds, normalize_title_key(title))
        meta = oa_map.get(key, {})
        abstract = meta.get("abstract", "")
        doi = normalize_doi_url(row.get("doi_or_url", "") or row.get("doi", "") or meta.get("doi_or_url_oa", ""))
        if not title:
            title = meta.get("title_oa", "")
        base_text = clean_text(" ".join([title, abstract]))
        rows.append({
            "audit_index": i,
            "dataset": ds,
            "title": title,
            "abstract": abstract,
            "doi_or_url": doi,
            "base_text": base_text,
            "source_csv": meta.get("source_csv", row.get("source_csv", "")),
            "openalex_id": meta.get("openalex_id", ""),
            "year": row.get("year", meta.get("year_oa", "")),
        })

    fetch_results: Dict[int, FetchResult] = {}
    if args.fetch_fulltext:
        to_fetch = [(idx, r["doi_or_url"]) for idx, r in enumerate(rows) if r["doi_or_url"]]
        if not args.quiet:
            print(f"Trying full-text/DOI retrieval for {len(to_fetch)} papers...")
        if args.doi_workers <= 1:
            fetcher = FullTextFetcher(args.timeout, args.sleep_sec)
            iterator = to_fetch
            if tqdm is not None and not args.quiet:
                iterator = tqdm(to_fetch, desc=f"{regime} full text", unit="paper", dynamic_ncols=True)
            for idx, url in iterator:
                fetch_results[idx] = fetcher.fetch(url)
        else:
            # Each worker creates its own session via helper.
            def work(item: Tuple[int, str]) -> Tuple[int, FetchResult]:
                idx, url = item
                fetcher = FullTextFetcher(args.timeout, args.sleep_sec)
                return idx, fetcher.fetch(url)
            with cf.ThreadPoolExecutor(max_workers=args.doi_workers) as ex:
                iterator = ex.map(work, to_fetch)
                if tqdm is not None and not args.quiet:
                    iterator = tqdm(iterator, total=len(to_fetch), desc=f"{regime} full text", unit="paper", dynamic_ncols=True)
                for idx, res in iterator:
                    fetch_results[idx] = res

    pattern_counts: Dict[str, Counter] = defaultdict(Counter)
    denominators: Dict[str, int] = Counter()
    audit_rows = []
    source_counter = Counter()
    matched_any_counter = Counter()

    iterator = enumerate(rows)
    if tqdm is not None and not args.quiet:
        iterator = tqdm(list(iterator), desc=f"{regime} pattern parse", unit="paper", dynamic_ncols=True)

    for idx, r in iterator:
        ds = r["dataset"]
        full_res = fetch_results.get(idx, FetchResult("", "metadata_only", r.get("doi_or_url", ""), ""))
        combined_text = clean_text(r["base_text"] + " " + full_res.text)
        text_available = len(combined_text) >= args.min_text_chars
        # Denominator is accessible papers that have enough text to assess. Since accessible papers
        # are already taken from the prior audit, this usually equals accessible papers except for
        # malformed rows with no title/abstract at all.
        if text_available:
            denominators[ds] += 1
        patterns, evidence = detect_pipeline_patterns(combined_text, args.method_window) if text_available else ([], {})
        if text_available and patterns:
            matched_any_counter[ds] += 1
            for ptn in patterns:
                pattern_counts[ds][ptn] += 1
        source = full_res.source if full_res.text else "metadata_only"
        source_counter[source] += 1
        audit_rows.append({
            "dataset": ds,
            "title": r["title"],
            "doi_or_url": r["doi_or_url"],
            "source_csv": r["source_csv"],
            "openalex_id": r["openalex_id"],
            "year": r["year"],
            "accessible_flag": flag,
            "text_available": text_available,
            "text_chars": len(combined_text),
            "text_source": source,
            "fetch_error": full_res.error,
            "patterns_detected": "; ".join(patterns),
            "num_patterns": len(patterns),
            **{f"pattern__{name}": int(name in patterns) for name in PATTERN_ORDER},
            **{f"evidence__{name}": evidence.get(name, "") for name in PATTERN_ORDER},
        })

    counts_df, prev_df = counts_to_tables(pattern_counts, denominators, add_total=not args.no_total_column)

    # Coverage table: prior audit accessible vs assessable text vs any detected pattern.
    all_datasets = sorted(accessible["dataset"].unique().tolist())
    coverage_rows = []
    for ds in all_datasets:
        accessible_n = int((accessible["dataset"] == ds).sum())
        assessable_n = int(denominators.get(ds, 0))
        any_pattern_n = int(matched_any_counter.get(ds, 0))
        coverage_rows.append({
            "dataset": pretty_dataset_name(ds),
            "accessible_papers": accessible_n,
            "assessable_text_papers": assessable_n,
            "papers_with_at_least_one_pattern": any_pattern_n,
            "assessable_over_accessible_percent": round(100.0 * assessable_n / accessible_n, 1) if accessible_n else 0.0,
            "any_pattern_over_assessable_percent": round(100.0 * any_pattern_n / assessable_n, 1) if assessable_n else 0.0,
        })
    coverage_df = pd.DataFrame(coverage_rows)

    prefix = f"{regime}_pipeline_patterns_from_audit"
    prev_df.to_csv(out_dir / f"{prefix}_prevalence_by_dataset.csv")
    counts_df.to_csv(out_dir / f"{prefix}_counts_by_dataset.csv")
    coverage_df.to_csv(out_dir / f"{prefix}_coverage_by_dataset.csv", index=False)
    pd.DataFrame(audit_rows).to_csv(out_dir / f"{prefix}_audit_log.csv", index=False)
    pd.DataFrame([{"text_source": k, "count": v} for k, v in source_counter.items()]).to_csv(out_dir / f"{prefix}_text_source_report.csv", index=False)

    (out_dir / f"{prefix}_prevalence_by_dataset.txt").write_text(df_to_pretty_text(prev_df), encoding="utf-8")
    (out_dir / f"{prefix}_counts_by_dataset.txt").write_text(df_to_pretty_text(counts_df), encoding="utf-8")
    caption = (
        f"{regime} regime: prevalence of pipeline architecture patterns across datasets. "
    )
    (out_dir / f"{prefix}_prevalence_by_dataset.tex").write_text(
        df_to_latex(prev_df, caption, f"tab:{regime}_pipeline_patterns"), encoding="utf-8"
    )

    report = {
        "regime": regime,
        "audit_log": str(audit_path),
        "openalex_dir": str(openalex_dir),
        "accessible_flag": flag,
        "audit_rows_total": int(len(audit)),
        "accessible_papers": int(len(accessible)),
        "assessable_papers": int(sum(denominators.values())),
        "papers_with_at_least_one_pattern": int(sum(matched_any_counter.values())),
        "fetch_fulltext": bool(args.fetch_fulltext),
        "text_source_counts": dict(source_counter),
        "patterns": PATTERN_ORDER,
    }
    (out_dir / f"{prefix}_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    if not args.quiet:
        print("\nPrevalence table:")
        print(df_to_pretty_text(prev_df))
        print("\nCoverage:")
        print(coverage_df.to_string(index=False))
        print(f"\nWrote outputs to: {out_dir.resolve()}")
    else:
        print(f"Wrote outputs to: {out_dir.resolve()}")
    return 0

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Parse pipeline architecture patterns from paper audit logs.")
    p.add_argument("--regime", default="H", choices=["S", "H", "M", "T"], help="Regime to process.")
    p.add_argument("--audit-results-dir", default="./regime_parse_outputs", help="Directory containing <REGIME>/<REGIME>_paper_audit_log.csv.")
    p.add_argument("--openalex-base-dir", default="./query_outputs", help="Directory containing <REGIME>/openalex_*_<REGIME>_ml_top350.csv.")
    p.add_argument("--output-dir", default="./pipeline_parse_output", help="Output directory.")
    p.add_argument("--accessible-flag", default="", help="Audit-log boolean column defining accessible papers. If omitted, auto-detected.")
    p.add_argument("--fetch-fulltext", action="store_true", default=True, help="Try DOI/URL landing pages and PDFs after title/abstract.")
    p.add_argument("--doi-workers", type=int, default=1, help="Parallel workers for DOI/full-text retrieval. Used only with --fetch-fulltext.")
    p.add_argument("--timeout", type=int, default=25, help="HTTP timeout in seconds.")
    p.add_argument("--sleep-sec", type=float, default=0.25, help="Polite sleep between requests per worker.")
    p.add_argument("--min-text-chars", type=int, default=80, help="Minimum combined metadata text chars to keep a paper assessable.")
    p.add_argument("--method-window", type=int, default=8000, help="Chars around method-like headings prioritized in matching; 0 disables section focus.")
    p.add_argument("--no-total-column", action="store_true", help="Do not add Total column to prevalence/count tables.")
    p.add_argument("--quiet", action="store_true", help="Reduce console output.")
    return p.parse_args()

if __name__ == "__main__":
    raise SystemExit(main())
