#!/usr/bin/env python3
"""
Dataset-Regime ML Model Parsing Script
--------------------------------------

Purpose
-------
Parses previously retrieved OpenAlex dataset-regime CSV files and performs
large-scale rule-based extraction of machine learning models from titles,
abstracts, and optionally DOI landing pages/full-text content.

The script is designed to support the four prediction regimes:

    S = structured multiscale prediction
    H = high-dimensional biomedical signals
    M = multimodal learning
    T = temporal and longitudinal modeling

The script:
1) loads one or more OpenAlex CSV exports generated by the dataset query pipeline
2) filters papers using regime-specific regex pattern libraries
3) extracts exact machine learning model names using extensive regex matching
4) maps exact models into broader model-family categories
5) optionally retrieves additional text from DOI landing pages or PDFs
6) identifies:
      - model occurances (labeled here "any-use" models)
      - dominant model occurances (labeled here "primary-only" models)
7) builds:
      - dataset-level model-family frequency tables
      - exact-model frequency tables
      - any-use and primary-only statistics
8) exports:
      - CSV summary tables
      - formatted TXT tables
      - formatted LaTeX tables
      - audit logs for every parsed paper
      - per-dataset count CSV files
9) generates model-family → exact-model mapping tables

"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys
import time
import json
import glob
import math
import warnings
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Iterable, Set

import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse

# Optional dependencies
try:
    from tqdm import tqdm
except Exception:  # pragma: no cover
    tqdm = None

try:
    import PyPDF2
except Exception:  # pragma: no cover
    PyPDF2 = None

warnings.filterwarnings("ignore")

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0 Safari/537.36"
)

HEADERS = {"User-Agent": USER_AGENT}

# -----------------------------------------------------------------------------
# Regime patterns
# -----------------------------------------------------------------------------
REGIME_PATTERNS: Dict[str, List[str]] = {
    "S": [
        r"\btabular\b",
        r"\bstructured data\b",
        r"\bstructured clinical data\b",
        r"\bclinical variables?\b",
        r"\bdemographic[s]?\b",
        r"\bquestionnaire[s]?\b",
        r"\brisk factor[s]?\b",
        r"\bcovariate[s]?\b",
        r"\bmultivariable\b",
        r"\brisk prediction\b",
        r"\brisk model\b",
        r"\bclinical data\b",
        r"\belectronic health record[s]?\b",
        r"\behr\b",
        r"\bpopulation[- ]based\b",
        r"\bepidemiolog(?:y|ical)\b",
        r"\bbiobank\b",
        r"\bcohort\b",
        r"\bsurvey\b",
    ],
    "H": [
        r"\bhigh[- ]dimensional\b",
        r"\bomics\b",
        r"\bgenomic[s]?\b",
        r"\btranscriptomic[s]?\b",
        r"\bproteomic[s]?\b",
        r"\bmetabolomic[s]?\b",
        r"\bgene expression\b",
        r"\bmicroarray\b",
        r"\bsequencing\b",
        r"\bnext[- ]generation sequencing\b",
        r"\bradiomic[s]?\b",
        r"\bhistopatholog(?:y|ical)\b",
        r"\bwhole slide image[s]?\b",
        r"\bmri\b",
        r"\bfmri\b",
        r"\bct\b",
        r"\bpet\b",
        r"\bimage classification\b",
        r"\bsegmentation\b",
        r"\bvoxel\b",
        r"\bpixel[- ]level\b",
    ],
    "M": [
        r"\bmultimodal\b",
        r"\bmulti[- ]modal\b",
        r"\bmultimodality\b",
        r"\bdata fusion\b",
        r"\bfusion model\b",
        r"\bfusion approach\b",
        r"\bmultisource\b",
        r"\bmulti[- ]source\b",
        r"\bheterogeneous data\b",
        r"\bheterogeneous modalities\b",
        r"\bclinical and imaging\b",
        r"\bclinical \+ imaging\b",
        r"\bimaging and clinical\b",
        r"\behr and imaging\b",
        r"\behr and genomics\b",
        r"\bmulti[- ]omics\b",
        r"\bwearable[s]?\b",
        r"\bsmartphone[s]?\b",
        r"\bmobile health\b",
        r"\bdigital phenotyping\b",
        r"\bbehavioral sensing\b",
        r"\bsensor fusion\b",
    ],
    "T": [
        r"\blongitudinal\b",
        r"\btime[- ]series\b",
        r"\btrajectory\b",
        r"\btrajectories\b",
        r"\bforecast(?:ing)?\b",
        r"\bfollow[- ]up\b",
        r"\bover time\b",
        r"\btemporal\b",
        r"\bsequential\b",
        r"\bdynamic\b",
        r"\bincident\b",
        r"\bsurvival\b",
        r"\bhazard\b",
        r"\bprogression\b",
        r"\bnext \d+\s*(?:day|days|week|weeks|month|months|year|years)\b",
        r"\bwithin \d+\s*(?:h|hr|hrs|hour|hours|day|days|week|weeks|month|months|year|years)\b",
        r"\bprediction horizon\b",
        r"\bprospective\b",
        r"\bretrospective cohort\b",
    ],
}

# -----------------------------------------------------------------------------
# Exact models -> family
# -----------------------------------------------------------------------------
MODEL_PATTERNS: List[Tuple[str, str, List[str]]] = [
    ("Autoencoder", "Deep learning", [r"\bauto[- ]?encoder[s]?\b", r"\bvariational auto[- ]?encoder[s]?\b", r"\bvae\b"]),
    ("CNN", "Deep learning", [r"\bcnn\b", r"convolutional neural network[s]?", r"\bconvnet[s]?\b"]),
    ("DNN", "Deep learning", [r"\bdnn\b", r"deep neural network[s]?", r"deep learning"]),
    ("GRU", "Deep learning", [r"\bgru\b", r"gated recurrent unit[s]?"]),
    ("Graph neural network", "Deep learning", [r"graph neural network[s]?", r"\bgnn\b", r"graph convolutional network[s]?", r"\bgcn\b"]),
    ("LSTM", "Deep learning", [r"\blstm\b", r"long short[- ]term memory"]),
    ("MLP", "Deep learning", [r"\bmlp\b", r"multilayer perceptron", r"multi[- ]layer perceptron"]),
    ("RNN", "Deep learning", [r"\brnn\b", r"recurrent neural network[s]?"]),
    ("TCN", "Deep learning", [r"temporal convolutional network[s]?", r"\btcn\b"]),
    ("Transformer", "Deep learning", [r"\btransformer[s]?\b", r"bert\b", r"attention[- ]based"]),
    ("AdaBoost", "Tree-based ensemble", [r"\badaboost\b"]),
    ("CatBoost", "Tree-based ensemble", [r"\bcatboost\b"]),
    ("Extra Trees", "Tree-based ensemble", [r"extra trees", r"extremely randomized trees"]),
    ("Gradient Boosting", "Tree-based ensemble", [r"gradient boosting", r"gradient boosted trees?"]),
    ("LightGBM", "Tree-based ensemble", [r"\blightgbm\b"]),
    ("Random Forest", "Tree-based ensemble", [r"random forest[s]?", r"\brf\b"]),
    ("XGBoost", "Tree-based ensemble", [r"\bxgboost\b", r"extreme gradient boosting"]),
    ("Elastic Net", "Linear / GLM", [r"elastic net"]),
    ("LASSO", "Linear / GLM", [r"\blasso\b"]),
    ("Linear Regression", "Linear / GLM", [r"linear regression"]),
    ("Logistic Regression", "Linear / GLM", [r"logistic regression", r"\blogit\b"]),
    ("Ridge Regression", "Linear / GLM", [r"ridge regression"]),
    ("Support Vector Machine", "Kernel / instance-based", [r"support vector machine[s]?", r"\bsvm\b", r"support vector regression", r"\bsvr\b"]),
    ("k-Nearest Neighbors", "Kernel / instance-based", [r"k[- ]nearest neighbors?", r"\bknn\b"]),
    ("Cox Proportional Hazards", "Survival models", [r"cox proportional hazards?", r"cox regression", r"\bcox model"]),
    ("Joint Model", "Survival models", [r"joint model[s]?"]),
    ("Kaplan–Meier", "Survival models", [r"kaplan[-– ]meier"]),
    ("Random Survival Forest", "Survival models", [r"random survival forest[s]?"]),
    ("ARIMA", "Probabilistic / statistical", [r"\barima\b"]),
    ("Bayesian Regression", "Probabilistic / statistical", [r"bayesian regression", r"bayes(?:ian)? model[s]?"]),
    ("Generalized Estimating Equations", "Probabilistic / statistical", [r"generalized estimating equations?", r"\bgee\b"]),
    ("Hidden Markov Model", "Probabilistic / statistical", [r"hidden markov model[s]?", r"\bhmm\b"]),
    ("Kalman Filter", "Probabilistic / statistical", [r"kalman filter[s]?"]),
    ("Markov Model", "Probabilistic / statistical", [r"markov model[s]?"]),
    ("Mixed-Effects Model", "Probabilistic / statistical", [r"mixed[- ]effects? model[s]?", r"mixed model[s]?", r"multilevel model[s]?"]),
    ("Naive Bayes", "Probabilistic / statistical", [r"naive bayes"]),
    ("Ensemble", "Ensemble / stacking", [r"\bensemble\b", r"stacking", r"stacked ensemble", r"blending"]),
    ("Decision Tree", "Other classical ML", [r"decision tree[s]?"]),
    ("Federated Learning", "Other classical ML", [r"federated learning"]),
    ("Reinforcement Learning", "Other classical ML", [r"reinforcement learning"]),
]

FAMILY_ORDER = [
    "Linear / GLM",
    "Deep learning",
    "Survival models",
    "Tree-based ensemble",
    "Kernel / instance-based",
    "Other classical ML",
    "Probabilistic / statistical",
    "Ensemble / stacking",
]

def slugify_dataset(path: str) -> str:
    name = Path(path).stem.lower()
    name = re.sub(r"^openalex_", "", name)
    name = re.sub(r"_[shmt]_ml_top\d+$", "", name)
    name = re.sub(r"[^a-z0-9]+", "_", name).strip("_")
    return name


def ensure_dir(path: str | Path) -> str:
    path = str(Path(path).resolve())
    Path(path).mkdir(parents=True, exist_ok=True)
    return path


def choose_column(df: pd.DataFrame, candidates: Iterable[str]) -> Optional[str]:
    lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower:
            return lower[cand.lower()]
    return None


def get_text_fields(row: pd.Series, title_col: str, abstract_col: Optional[str], goal_col: Optional[str]) -> Tuple[str, str, str]:
    title = str(row.get(title_col, "") or "")
    abstract = str(row.get(abstract_col, "") or "") if abstract_col else ""
    goal = str(row.get(goal_col, "") or "") if goal_col else ""
    return title, abstract, goal


def normalize_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text or " ")
    return text.strip()


def regime_score(text: str, regime: str) -> int:
    pats = REGIME_PATTERNS.get(regime, [])
    return sum(1 for p in pats if re.search(p, text, flags=re.I))


def detect_models(text: str) -> Tuple[List[str], Dict[str, str]]:
    exact: List[str] = []
    mapping: Dict[str, str] = {}
    for model, family, patterns in MODEL_PATTERNS:
        if any(re.search(p, text, flags=re.I) for p in patterns):
            exact.append(model)
            mapping[model] = family
    return exact, mapping


def choose_primary_model(text: str, exact_models: List[str], model_to_family: Dict[str, str]) -> Tuple[Optional[str], Optional[str], str]:
    if not exact_models:
        return None, None, "no_identifiable_model"

    primary_cues = [
        r"we (?:developed|proposed|used|trained|applied|implemented|constructed) (?:an?|the)?\s*{name}",
        r"{name} (?:model|classifier|regressor|framework|approach)",
        r"using (?:an?|the)?\s*{name}",
        r"based on (?:an?|the)?\s*{name}",
    ]

    scores: Dict[str, int] = {m: 0 for m in exact_models}
    for m in exact_models:
        base = re.escape(m)
        for cue in primary_cues:
            if re.search(cue.format(name=base), text, flags=re.I):
                scores[m] += 2
        if re.search(base, text, flags=re.I):
            scores[m] += 1

    if not scores:
        return None, None, "primary_unclear"

    best = max(scores.values())
    winners = [m for m, s in scores.items() if s == best and s > 0]
    if len(winners) != 1:
        return None, None, "primary_unclear"

    m = winners[0]
    return m, model_to_family[m], "ok"


def fetch_url_text(url: str, timeout: int = 25) -> str:
    try:
        r = requests.get(url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        r.raise_for_status()
        ctype = (r.headers.get("Content-Type") or "").lower()
        if "pdf" in ctype or url.lower().endswith(".pdf"):
            return extract_pdf_text_bytes(r.content)
        soup = BeautifulSoup(r.text, "html.parser")
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()
        return normalize_text(soup.get_text(" ", strip=True))
    except Exception:
        return ""


def extract_pdf_text_bytes(data: bytes) -> str:
    if PyPDF2 is None:
        return ""
    try:
        reader = PyPDF2.PdfReader(io.BytesIO(data), strict=False)
        pages = []
        for page in reader.pages[:25]:
            try:
                pages.append(page.extract_text() or "")
            except Exception:
                continue
        return normalize_text(" ".join(pages))
    except Exception:
        return ""


def maybe_fetch_extra_text(doi_or_url: str, disable_fetch: bool, timeout: int, sleep_sec: float) -> str:
    if disable_fetch:
        return ""
    value = (doi_or_url or "").strip()
    if not value:
        return ""
    candidates = [u.strip() for u in re.split(r"[;,\s]+", value) if u.strip()]
    for cand in candidates:
        if cand.startswith("10."):
            cand = f"https://doi.org/{cand}"
        elif not re.match(r"https?://", cand, flags=re.I) and "/" in cand and cand.startswith("10."):
            cand = f"https://doi.org/{cand}"
        elif not re.match(r"https?://", cand, flags=re.I):
            continue
        text = fetch_url_text(cand, timeout=timeout)
        time.sleep(sleep_sec)
        if text:
            return text
    return ""


def is_relevant_to_regime(text: str, regime: str, exact_models: List[str], min_score: int = 1) -> bool:
    score = regime_score(text, regime)
    if regime == "S":
        # Permissive logic for S: if there is at least one structured cue, or at least one model and no stronger H/M/T cues.
        if score >= 1:
            return True
        other_scores = {r: regime_score(text, r) for r in ["H", "M", "T"]}
        if exact_models and max(other_scores.values(), default=0) == 0:
            return True
        return False
    return score >= min_score


# -----------------------------------------------------------------------------
# Table builders
# -----------------------------------------------------------------------------
def counts_to_percentage_table(dataset_to_counter: Dict[str, Counter], dataset_to_n: Dict[str, int], row_order: Optional[List[str]] = None) -> pd.DataFrame:
    datasets = sorted(dataset_to_counter)
    rows: Set[str] = set()
    for c in dataset_to_counter.values():
        rows.update(c.keys())
    ordered_rows = [r for r in (row_order or []) if r in rows] + sorted(r for r in rows if r not in set(row_order or []))
    data = {}
    total_counter = Counter()
    total_n = 0
    for ds in datasets:
        n = dataset_to_n.get(ds, 0)
        col = []
        for row in ordered_rows:
            val = dataset_to_counter[ds].get(row, 0)
            col.append(round((100.0 * val / n), 1) if n else 0.0)
            total_counter[row] += val
        data[ds] = col
        total_n += n
    total_vals = [round((100.0 * total_counter[row] / total_n), 1) if total_n else 0.0 for row in ordered_rows]
    df = pd.DataFrame(data, index=ordered_rows)
    df["Total"] = total_vals
    df.loc["Papers (N)"] = [dataset_to_n.get(ds, 0) for ds in datasets] + [total_n]
    return df


def counts_to_count_table(counter: Counter, n: int) -> pd.DataFrame:
    items = sorted(counter.items(), key=lambda x: (-x[1], x[0].lower()))
    df = pd.DataFrame({"Count": [v for _, v in items]}, index=[k for k, _ in items])
    df.loc["Papers (N)"] = n
    return df


def df_to_pretty_text(df: pd.DataFrame) -> str:
    show = df.copy().astype(object)
    for idx in show.index:
        for col in show.columns:
            val = show.loc[idx, col]
            try:
                if idx == "Papers (N)":
                    show.loc[idx, col] = str(int(float(val)))
                else:
                    show.loc[idx, col] = f"{float(val):.1f}"
            except Exception:
                show.loc[idx, col] = str(val)
    return show.to_string()


def latex_escape(s: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    for k, v in repl.items():
        s = s.replace(k, v)
    return s


def df_to_mdpi_latex(df: pd.DataFrame, caption: str, label: str) -> str:
    cols = df.columns.tolist()
    align = "l" + "r" * len(cols)
    lines = [
        r"\begin{table*}[ht]",
        r"\centering",
        rf"\caption{{{latex_escape(caption)}}}",
        rf"\label{{{latex_escape(label)}}}",
        rf"\begin{{tabular}}{{{align}}}",
        r"\toprule",
        "Model family" + " & " + " & ".join(latex_escape(str(c)) for c in cols) + r" \\",
        r"\midrule",
    ]
    for idx in df.index:
        vals = []
        for col in cols:
            x = df.loc[idx, col]
            if idx == "Papers (N)":
                vals.append(str(int(float(x))))
            else:
                vals.append(f"{float(x):.1f}")
        if idx == "Papers (N)":
            lines.append(r"\midrule")
        lines.append(latex_escape(str(idx)) + " & " + " & ".join(vals) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}"])
    return "\n".join(lines)


def family_model_map_latex(family_to_models: Dict[str, Set[str]], regime: str) -> str:
    lines = [
        r"\begin{table}[ht]",
        r"\centering",
        rf"\caption{{Model families and exact models identified in the {latex_escape(regime)} regime.}}",
        rf"\label{{tab:{latex_escape(regime)}_model_families}}",
        r"\begin{tabular}{p{4.2cm} p{10.5cm}}",
        r"\toprule",
        r"\textbf{Model family} & \textbf{Exact models identified} \\",
        r"\midrule",
    ]
    for family in FAMILY_ORDER:
        models = sorted(family_to_models.get(family, set()))
        if not models:
            continue
        lines.append(latex_escape(family) + " & " + latex_escape("; ".join(models)) + r" \\")
        lines.append("")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# Per-dataset extra outputs
# -----------------------------------------------------------------------------
def write_extra_dataset_count_csvs(
    out_dir: str,
    regime: str,
    dataset_any_model_counts: Dict[str, Counter],
    dataset_any_family_counts: Dict[str, Counter],
    dataset_primary_model_counts: Dict[str, Counter],
    dataset_primary_family_counts: Dict[str, Counter],
    dataset_any_n: Dict[str, int],
    dataset_primary_n: Dict[str, int],
) -> int:
    extra_dir = ensure_dir(Path(out_dir) / f"{regime}_extra_dataset_counts")
    manifest_rows = []
    written = 0

    all_datasets = sorted(set(dataset_any_model_counts) | set(dataset_any_family_counts) | set(dataset_primary_model_counts) | set(dataset_primary_family_counts))
    for ds in all_datasets:
        bundle = [
            (f"{ds}_any_use_model_counts.csv", counts_to_count_table(dataset_any_model_counts.get(ds, Counter()), dataset_any_n.get(ds, 0))),
            (f"{ds}_any_use_family_counts.csv", counts_to_count_table(dataset_any_family_counts.get(ds, Counter()), dataset_any_n.get(ds, 0))),
            (f"{ds}_primary_only_model_counts.csv", counts_to_count_table(dataset_primary_model_counts.get(ds, Counter()), dataset_primary_n.get(ds, 0))),
            (f"{ds}_primary_only_family_counts.csv", counts_to_count_table(dataset_primary_family_counts.get(ds, Counter()), dataset_primary_n.get(ds, 0))),
        ]
        for fname, df in bundle:
            fpath = Path(extra_dir) / fname
            df.to_csv(fpath)
            exists = fpath.exists()
            written += int(exists)
            manifest_rows.append({"dataset": ds, "file": fname, "path": str(fpath.resolve()), "exists": exists})

    pd.DataFrame(manifest_rows).to_csv(Path(extra_dir) / "manifest.csv", index=False)
    return written


# -----------------------------------------------------------------------------
# Main parsing
# -----------------------------------------------------------------------------
def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    out_dir = ensure_dir(args.output_dir)
    csv_paths = sorted(glob.glob(str(input_dir / args.input_glob)))
    if not csv_paths:
        print(f"No files matched: {input_dir / args.input_glob}", file=sys.stderr)
        return 1

    dataset_any_model_counts: Dict[str, Counter] = defaultdict(Counter)
    dataset_any_family_counts: Dict[str, Counter] = defaultdict(Counter)
    dataset_primary_model_counts: Dict[str, Counter] = defaultdict(Counter)
    dataset_primary_family_counts: Dict[str, Counter] = defaultdict(Counter)
    dataset_any_n: Dict[str, int] = defaultdict(int)
    dataset_primary_n: Dict[str, int] = defaultdict(int)
    family_to_models: Dict[str, Set[str]] = defaultdict(set)
    audit_rows: List[dict] = []
    summary_rows: List[dict] = []

    for csv_path in csv_paths:
        dataset = slugify_dataset(csv_path)
        df = pd.read_csv(csv_path)
        title_col = choose_column(df, ["title"])
        abstract_col = choose_column(df, ["abstract"])
        goal_col = choose_column(df, ["Goal", "goal"])
        doi_col = choose_column(df, ["DOI", "doi", "doi_url", "link", "url", "links"])
        if title_col is None:
            print(f"Skipping {csv_path}: no title column.", file=sys.stderr)
            continue

        total = len(df)
        used_any = 0
        used_primary = 0

        iterator = df.iterrows()
        if tqdm is not None:
            iterator = tqdm(iterator, total=total, desc=f"{dataset}", disable=False, leave=True)

        for idx, row in iterator:
            title, abstract, goal = get_text_fields(row, title_col, abstract_col, goal_col)
            base_text = normalize_text(" ".join([title, abstract, goal]))
            doi_or_url = str(row.get(doi_col, "") or "") if doi_col else ""
            extra_text = maybe_fetch_extra_text(doi_or_url, args.disable_doi_fetch, args.timeout, args.sleep_sec)
            full_text = normalize_text(" ".join([base_text, extra_text]))
            exact_models, model_to_family = detect_models(full_text)
            relevant = is_relevant_to_regime(full_text, args.regime, exact_models, min_score=args.min_regime_score)

            include_any = bool(relevant and exact_models)
            primary_model, primary_family, primary_reason = choose_primary_model(full_text, exact_models, model_to_family) if include_any else (None, None, "not_included_any")
            include_primary = bool(primary_model)

            if include_any:
                used_any += 1
                dataset_any_n[dataset] += 1
                for model in sorted(set(exact_models)):
                    dataset_any_model_counts[dataset][model] += 1
                    fam = model_to_family[model]
                    dataset_any_family_counts[dataset][fam] += 1
                    family_to_models[fam].add(model)

            if include_primary:
                used_primary += 1
                dataset_primary_n[dataset] += 1
                dataset_primary_model_counts[dataset][primary_model] += 1
                dataset_primary_family_counts[dataset][primary_family] += 1

            audit_rows.append(
                {
                    "dataset": dataset,
                    "source_csv": os.path.basename(csv_path),
                    "row_index": idx,
                    "title": title,
                    "doi_or_url": doi_or_url,
                    "regime": args.regime,
                    "regime_score": regime_score(full_text, args.regime),
                    "relevant": relevant,
                    "models_detected": "; ".join(exact_models),
                    "families_detected": "; ".join(sorted({model_to_family[m] for m in exact_models})),
                    "include_any_use": include_any,
                    "primary_model": primary_model or "",
                    "primary_family": primary_family or "",
                    "include_primary_only": include_primary,
                    "primary_reason": primary_reason,
                }
            )

            if tqdm is not None and hasattr(iterator, "set_postfix_str"):
                iterator.set_postfix_str(f"parsed={used_any}/{total}")

        summary_rows.append({"dataset": dataset, "provided": total, "used_any": used_any, "used_primary": used_primary})

    # Main family percentage tables
    any_df = counts_to_percentage_table(dataset_any_family_counts, dataset_any_n, FAMILY_ORDER)
    primary_df = counts_to_percentage_table(dataset_primary_family_counts, dataset_primary_n, FAMILY_ORDER)
    any_model_df = counts_to_percentage_table(dataset_any_model_counts, dataset_any_n)
    primary_model_df = counts_to_percentage_table(dataset_primary_model_counts, dataset_primary_n)

    # Write outputs
    pd.DataFrame(audit_rows).to_csv(Path(out_dir) / f"{args.regime}_paper_audit_log.csv", index=False)
    pd.DataFrame(summary_rows).to_csv(Path(out_dir) / f"{args.regime}_summary_counts.csv", index=False)

    any_df.to_csv(Path(out_dir) / f"{args.regime}_any_use_table.csv")
    primary_df.to_csv(Path(out_dir) / f"{args.regime}_primary_only_table.csv")
    any_model_df.to_csv(Path(out_dir) / f"{args.regime}_any_use_model_table.csv")
    primary_model_df.to_csv(Path(out_dir) / f"{args.regime}_primary_only_model_table.csv")

    (Path(out_dir) / f"{args.regime}_any_use_table.txt").write_text(df_to_pretty_text(any_df), encoding="utf-8")
    (Path(out_dir) / f"{args.regime}_primary_only_table.txt").write_text(df_to_pretty_text(primary_df), encoding="utf-8")
    (Path(out_dir) / f"{args.regime}_any_use_model_table.txt").write_text(df_to_pretty_text(any_model_df), encoding="utf-8")
    (Path(out_dir) / f"{args.regime}_primary_only_model_table.txt").write_text(df_to_pretty_text(primary_model_df), encoding="utf-8")

    (Path(out_dir) / f"{args.regime}_any_use_table.tex").write_text(
        df_to_mdpi_latex(any_df, f"{args.regime} regime: any-use model-family frequencies across datasets.", f"tab:{args.regime}_any_use"),
        encoding="utf-8",
    )
    (Path(out_dir) / f"{args.regime}_primary_only_table.tex").write_text(
        df_to_mdpi_latex(primary_df, f"{args.regime} regime: primary-only model-family frequencies across datasets.", f"tab:{args.regime}_primary_only"),
        encoding="utf-8",
    )
    (Path(out_dir) / f"{args.regime}_family_model_map.tex").write_text(
        family_model_map_latex(family_to_models, args.regime),
        encoding="utf-8",
    )

    report = {
        "regime": args.regime,
        "input_dir": str(input_dir.resolve()),
        "input_glob": args.input_glob,
        "output_dir": str(Path(out_dir).resolve()),
        "files_processed": len(csv_paths),
        "summary": summary_rows,
    }
    (Path(out_dir) / f"{args.regime}_report.txt").write_text(json.dumps(report, indent=2), encoding="utf-8")

    if args.extra_dataset_count_csvs:
        written = write_extra_dataset_count_csvs(
            out_dir,
            args.regime,
            dataset_any_model_counts,
            dataset_any_family_counts,
            dataset_primary_model_counts,
            dataset_primary_family_counts,
            dataset_any_n,
            dataset_primary_n,
        )
        print(f"[extra] Target directory: {Path(out_dir).resolve() / (args.regime + '_extra_dataset_counts')}", file=sys.stderr)
        print(f"[extra] Files written: {written}", file=sys.stderr)

    summary_df = pd.DataFrame(summary_rows)
    if not summary_df.empty:
        print(summary_df.to_string(index=False))
    print(f"Output directory: {Path(out_dir).resolve()}")
    return 0


# -----------------------------------------------------------------------------
# Utilities
# -----------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Parse dataset-regime CSVs and build ML model tables.")

    # EXAMPLE TO RUN FOR "T" REGIME
    # p.add_argument("--input-glob", default="openalex_*_T_ml_top350.csv", help="Glob for input CSV files.")
    # p.add_argument("--input-dir", default="./query_outputs/T/", help="Directory containing CSV files.")
    # p.add_argument("--regime", default="T", choices=["S", "H", "M", "T"], help="Target regime.")

    # EXAMPLE TO RUN FOR "S" REGIME
    # p.add_argument("--input-glob", default="openalex_*_S_ml_top350.csv", help="Glob for input CSV files.")
    # p.add_argument("--input-dir", default="./query_outputs/S/", help="Directory containing CSV files.")
    # p.add_argument("--regime", default="S", choices=["S", "H", "M", "T"], help="Target regime.")

    # EXAMPLE TO RUN FOR "M" REGIME
    # p.add_argument("--input-glob", default="openalex_*_M_ml_top350.csv", help="Glob for input CSV files.")
    # p.add_argument("--input-dir", default="./query_outputs/M/", help="Directory containing CSV files.")
    # p.add_argument("--regime", default="M", choices=["S", "H", "M", "T"], help="Target regime.")

    # EXAMPLE TO RUN FOR "H" REGIME
    p.add_argument("--input-glob", default="openalex_*_H_ml_top350.csv", help="Glob for input CSV files.")
    p.add_argument("--input-dir", default="./query_outputs/H/", help="Directory containing CSV files.")
    p.add_argument("--regime", default="H", choices=["S", "H", "M", "T"], help="Target regime.")

    p.add_argument("--output-dir", default="outputs_regime_parse", help="Output directory.")
    p.add_argument("--disable-doi-fetch", action="store_true", help="Do not fetch DOI landing pages/full text.")
    p.add_argument("--sleep-sec", type=float, default=0.5, help="Sleep between DOI requests.")
    p.add_argument("--timeout", type=int, default=25, help="HTTP timeout in seconds.")
    p.add_argument("--quiet", action="store_true", help="Show only per-file progress bars and a final summary.")
    p.add_argument("--extra-dataset-count-csvs", default=True, action="store_true", help="Write per-dataset count CSVs for exact models and families.")
    p.add_argument("--force-extra-dataset-count-csvs", default=True, action="store_true", help="Force per-dataset count CSVs on even if no CLI flag is passed.")
    p.add_argument("--min-regime-score", type=int, default=1, help="Minimum pattern matches required for H/M/T. S uses permissive logic.")
    args = p.parse_args()
    if args.force_extra_dataset_count_csvs:
        args.extra_dataset_count_csvs = True
    return args

if __name__ == "__main__":
    raise SystemExit(main())
